version: '3.10'
services:
  dev:
    build: .
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
    restart: always
  test:
    build: .
    volumes:
      - .:/app
    environment:
      FLASK_ENV: testing
    command: python -m unittest discover -s tests
  prod:
      build: .
      volumes:
          - .:/app
      environment:
          FLASK_ENV: production
      restart: always